#!/bin/sh

START_HOUR=7

if [ `uname` = 'FreeBSD' ]
then
	start=`date -v${START_HOUR}H -v0M -v0S +%s`
	finish=`date -v${START_HOUR}H -v0M -v0S -v+1d +%s`
else
	# Assume we have GNU date
	start=`date --date "${START_HOUR} today" +%s`
	finish=`date --date "${START_HOUR} tomorrow" +%s`
fi

bin/bikesched_slice "${start}" "${finish}"
